name: sae_mobile_2025
description: "SAE Mobile 2025 - IUTables'O."

# Empêche la publication accidentelle sur pub.dev
publish_to: 'none'

# Définition de la version de l'application
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.1
  google_maps_flutter_web: ^0.5.11
  supabase_flutter: ^2.0.0
  flutter_map: ^0.14.0
  latlong2: ^0.8.0
  # Icônes pour iOS (Cupertino)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter pour encourager les bonnes pratiques de codage
  flutter_lints: ^5.0.0

flutter:
  # Permet l'utilisation des icônes Material
  uses-material-design: true

  # Ajout d'assets (exemples commentés)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Ajout de polices personnalisées (exemples commentés)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
